feat: add condition notion link
TeamBookTez/booktez-client pull request #268
Opened 2022-04-21 10:46 UTC by joohaem

## 📌 내용

- 회원가입 약관 동의에 노션 링크 첨부하였습니다

2022-04-23 05:25 UTC, soryeongk approved these changes

2022-04-28 09:43 UTC, soryeongk approved these changes

2022-04-28 09:43 UTC, soryeongk requested changes

2022-04-28 09:43 UTC, soryeongk commented on src/components/signup/FirstStep.tsx
> +  console.log(isEmailEmpty, isEmailError, isAgreeCondition);
ㅇㅉㅌㅂ

2022-04-28 09:44 UTC, soryeongk approved these changes

2022-04-30 06:14 UTC, joohaem commented on src/components/signup/FirstStep.tsx
> +  console.log(isEmailEmpty, isEmailError, isAgreeCondition);
zz;

2022-05-09 16:14 UTC, merged